slide_configs: "111"
channel_factor: 1
trans_type: "hybrid"
econvs_type: "dwpatchconv"
enc_act: 'ReLU'
embed_dim_div: 2

input_projection:
  mlp_ratio: 0.5
  activation: null
  dropout: 0.05
  prenorm: false
  bias: false
  drop_first: false

token_init_types: ['lrn1e-4']
global_strategy: 'identity'
  
ff_ratio: 2
attn_drop: 0.05
proj_drop: 0.0
drop_path: 0.0
window_size: 3
share_qkv: false

pos_emb: 'rpb'
pos_std: 0.02

kernel_size: 2
stride: 2
dilation: 1
conv_bias: false
edge_mode: count
edge_eps: 1e-6
conv_norm_position: pre
